spring:
  activemq:
    broker-url: tcp://120.78.197.250:61616
  jms:
    pub-sub-domain: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
  datasource:
    url: jdbc:mysql://120.78.197.250:3306/manager?user=manager&password=PYsrCzDbnFwdPLAh&useUnicode=true&characterEncoding=utf-8
  jpa:
    show-sql: true
server:
  context-path: /manager
  port: 8081
swagger:
  groupName: manager
  basePackage: com.powderblue.manager.controller
activemq:
  broker-url: tcp://120.78.197.250:61616
jms:
  pub-sub-domain: true